# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_proficiency', models.CharField(blank=True, choices=[(1, b'Confident in English-speaking'), (2, b'Knows English but not confident'), (3, b'Confident in Hindi'), (4, b'Not much confident in speaking')], max_length=50, null=True)),
                ('looks', models.CharField(blank=True, choices=[(b'classy', b'Classy'), (b'cool', b'Cool'), (b'decent', b'Decent'), (b'basic', b'Basic'), (b'above-average', b'Above Average'), (b'average', b'Average'), (b'below-average', b'Below Average')], max_length=50, null=True)),
                ('open_to_which_kind_of_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Open to which kind of jobs / workprofiles')),
                ('pay_scale', models.CharField(blank=True, max_length=100, null=True)),
                ('comfortable_travelling_outdoor', models.BooleanField(default=False)),
                ('comfortable_for_liquor_promotion', models.BooleanField(default=False)),
                ('comfortable_working_at_odd_timings', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Candidate Attributes (to be filled only if user type is cordinator)',
            },
        ),
        migrations.CreateModel(
            name='CandidateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Attributes (to be filled only if user type is client)',
            },
        ),
        migrations.CreateModel(
            name='CordinatorAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_for', models.CharField(blank=True, choices=[(b'event-agencies', b'Event Agencies'), (b'clients', b'Clients')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Cordinator Attributes (to be filled only if user type is cordinator)',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(unique=True)),
                ('whatsapp_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.uploadpath)),
                ('blacklist_flag', models.IntegerField(default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Area')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.City')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.State')),
            ],
            options={
                'verbose_name': 'Create / Modify User',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserRole'),
        ),
        migrations.AddField(
            model_name='cordinatorattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetail'),
        ),
        migrations.AddField(
            model_name='clientattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetail'),
        ),
        migrations.AddField(
            model_name='candidateattribute',
            name='candidate_profile',
            field=models.ManyToManyField(to='users.CandidateType'),
        ),
        migrations.AddField(
            model_name='candidateattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetail'),
        ),
    ]
