# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateattribute',
            name='language_proficiency',
            field=models.CharField(blank=True, choices=[(1, b'Confident in English-speaking'), (2, b'Knows English but not confident'), (3, b'Confident in Hindi'), (4, b'Not much confident in speaking')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateattribute',
            name='looks',
            field=models.CharField(blank=True, choices=[(b'classy', b'Classy'), (b'cool', b'Cool'), (b'decent', b'Decent'), (b'basic', b'Basic'), (b'above-average', b'Above Average'), (b'average', b'Average'), (b'below-average', b'Below Average')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateattribute',
            name='open_to_which_kind_of_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Open to which kind of jobs / workprofiles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blacklist_flag',
            field=models.IntegerField(default=0),
        ),
    ]
