# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170621_0655'),
        ('events', '0004_auto_20170621_0655'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cordinator',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client extra information'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users extra detail'},
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Cordinator',
        ),
    ]
