# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_highest_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateattribute',
            name='comfortable_for_liquor_promotion',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateattribute',
            name='comfortable_travelling_outdoor',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateattribute',
            name='comfortable_working_at_odd_timings',
            field=models.IntegerField(default=False),
        ),
    ]
