# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20170624_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateattribute',
            options={'verbose_name': 'Candidate Attributes (to be filled only if user type is cordinator)'},
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('id', 'auth_user')]),
        ),
    ]
