# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170621_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
