# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170625_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
