# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170626_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateattribute',
            name='candidate_profile',
            field=models.ManyToManyField(to='users.CandidateType'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
