# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170626_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
