# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170626_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'Create User'},
        ),
    ]
