# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170701_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'Create / Modify User'},
        ),
    ]
