# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_status_datetime', models.DateTimeField(auto_now_add=True)),
                ('allocation_status', models.CharField(choices=[(b'applied', b'Applied'), (b'shortlisted', b'Shortlisted'), (b'rejected', b'Rejected'), (b'selected', b'Selected'), (b'backup', b'Backup'), (b'working', b'Working'), (b'backed-out', b'Backed out')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('briefing_datetime', models.DateTimeField(blank=True, null=True)),
                ('briefing_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_number', models.BigIntegerField(blank=True, null=True)),
                ('is_onboard', models.BooleanField(default=False)),
                ('total_payment', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_type', models.CharField(max_length=20, verbose_name=users.models.CandidateType)),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'a', b'Any')], max_length=20)),
                ('no_of_candidates', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('daily_wage_per_candidate', models.IntegerField()),
                ('dress_code', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_class', models.CharField(blank=True, choices=[(b'A+', b'A+'), (b'A', b'A'), (b'B', b'B')], max_length=10, null=True, verbose_name='class')),
                ('communication_criteria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_datetime', models.DateTimeField(auto_now_add=True)),
                ('confirmation_status', models.CharField(choices=[(b'applied', b'Applid'), (b'wl', b'WL')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
