# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:48
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_datetime', models.DateTimeField(auto_now_add=True)),
                ('allocation_status', models.CharField(choices=[(b'shortlisted', b'Shortlisted'), (b'rejected', b'Rejected'), (b'positions-full', b'Position Full'), (b'backup', b'Backup'), (b'working', b'Working'), (b'backed-out', b'Backed out'), (b'completed', b'Completed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('overview', ckeditor.fields.RichTextField()),
                ('venue', models.CharField(max_length=100)),
                ('briefing_datetime', models.DateTimeField(blank=True, null=True)),
                ('briefing_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_number', models.BigIntegerField(blank=True, null=True)),
                ('is_onboard', models.BooleanField(default=False)),
                ('total_payment', models.BigIntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.City')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'a', b'Any')], max_length=20)),
                ('no_of_candidates', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('daily_wage_per_candidate', models.IntegerField()),
                ('dress_code', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_class', models.CharField(blank=True, choices=[(b'A+', b'A+'), (b'A', b'A'), (b'B', b'B'), (b'any', b'Any')], max_length=10, null=True, verbose_name='class')),
                ('communication_criteria', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CandidateType')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[(b'applied', b'Applied'), (b'wl', b'WL')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RequirementApplication'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementapplication',
            unique_together=set([('requirement', 'candidate')]),
        ),
    ]
