# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        ('master', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementallocation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='requirementallocation',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Area'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='users.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RequirementAllocation'),
        ),
    ]
