# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsrequirement',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'a', b'Any')], max_length=20),
        ),
    ]
