# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170624_1815'),
        ('events', '0002_auto_20170624_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_datetime', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[(b'applied', b'Applied'), (b'wl', b'WL')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='requirementallocation',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='requirementallocation',
            name='requirement',
        ),
        migrations.AlterField(
            model_name='allocationstatus',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RequirementApplication'),
        ),
        migrations.AlterField(
            model_name='allocationstatus',
            name='allocation_status',
            field=models.CharField(choices=[(b'shortlisted', b'Shortlisted'), (b'rejected', b'Rejected'), (b'backup', b'Backup'), (b'working', b'Working'), (b'backed-out', b'Backed out')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='candidate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CandidateType'),
        ),
        migrations.DeleteModel(
            name='RequirementAllocation',
        ),
        migrations.AddField(
            model_name='requirementapplication',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Requirement'),
        ),
    ]
