# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170807_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='test des'),
            preserve_default=False,
        ),
    ]
