# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0002_auto_20170621_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='briefing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='briefing_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Cordinator'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_payment',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsrequirement',
            name='candidate_class',
            field=models.CharField(blank=True, choices=[(b'A+', b'A+'), (b'A', b'A'), (b'B', b'B')], max_length=10, null=True, verbose_name='class'),
        ),
        migrations.AddField(
            model_name='eventsrequirement',
            name='communication_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsrequirement',
            name='dress_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsrequirement',
            name='work_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
