# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170625_1728'),
        ('events', '0003_auto_20170624_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirementapplication',
            unique_together=set([('requirement', 'candidate')]),
        ),
    ]
