# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170818_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
