# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170621_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_made_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='users.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
