# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_area'),
        ('events', '0004_auto_20170621_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.Area'),
            preserve_default=False,
        ),
    ]
