# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170625_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 25, 17, 45, 27, 759833)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 25, 17, 45, 33, 296837)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
