# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocationstatus',
            old_name='allocation_status_datetime',
            new_name='allocation_datetime',
        ),
        migrations.RenameField(
            model_name='allocationstatus',
            old_name='allocation',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='event',
            name='overview',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
