# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170626_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementapplication',
            old_name='allocation_datetime',
            new_name='application_datetime',
        ),
    ]
