# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170907_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
