# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170630_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 1, 6, 41, 2, 202907)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allocationstatus',
            name='allocation_status',
            field=models.CharField(choices=[(b'shortlisted', b'Shortlisted'), (b'rejected', b'Rejected'), (b'positions-full', b'Position Full'), (b'backup', b'Backup'), (b'working', b'Working'), (b'backed-out', b'Backed out')], max_length=50),
        ),
        migrations.AlterField(
            model_name='allocationstatus',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RequirementApplication', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='overview',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='candidate_class',
            field=models.CharField(blank=True, choices=[(b'A+', b'A+'), (b'A', b'A'), (b'B', b'B'), (b'any', b'Any')], max_length=10, null=True, verbose_name='class'),
        ),
    ]
