# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170908_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
