# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170701_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationstatus',
            name='allocation_status',
            field=models.CharField(choices=[(b'shortlisted', b'Shortlisted'), (b'rejected', b'Rejected'), (b'positions-full', b'Position Full'), (b'backup', b'Backup'), (b'working', b'Working'), (b'backed-out', b'Backed out'), (b'completed', b'Completed')], max_length=50),
        ),
    ]
