# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_content', ckeditor.fields.RichTextField()),
                ('aboutus_content', ckeditor.fields.RichTextField()),
                ('contactus_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
