# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 11:29
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscellanous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('show_on_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('commonpublish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miscellanous.CommonPublish')),
            ],
            bases=('miscellanous.commonpublish',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('commonpublish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miscellanous.CommonPublish')),
            ],
            bases=('miscellanous.commonpublish',),
        ),
        migrations.AddField(
            model_name='commonpublish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
