# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellanous', '0004_miscellaneous_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
